base:
  metrics: ['Recall(k=20)', 'Recall(k=40)','NDCG(k=20)','NDCG(k=40)', 'HitRate(k=20)','HitRate(k=40)','Coverage(k=20)','Coverage(k=40)','IHC(k=20)','IHC(k=40)']
  optimizer: Adam
  lr: 0.001
  per_eval: 1
  emb_lambda: 0.0001
  gpu: 0
  loss: PairwiseLogisticLoss
  save_model_path: "./save_model/"
  is_pretrained: False
  is_save_embedding: False
  num_epochs: 1000
  weight_decay: 8e-6